RF_VARIABLE = 'ALB.SR4.B{beam}:FGC_FREQ'

TUNE_VARS = ['LHC.BQBBQ.CONTINUOUS_HS.B{beam}:EIGEN_FREQ_1',
             'LHC.BQBBQ.CONTINUOUS_HS.B{beam}:EIGEN_FREQ_2']
X_VAR_INDICATOR = 'EIGEN_FREQ_1'

DPP_FILE = "dpp_B{beam}.tfs"
CLEANED_DPP_FILE = "dpp_cleaned_B{beam}.tfs"
